#!/usr/bin/env python3
"""Phalanx Swarm v2.0-OMEGA — Report Generator

Generates markdown reports for stakeholders, auto-commits to GitHub,
creates Linear issues, and updates Notion/Airtable.
"""

import json
import os
import sqlite3
from datetime import datetime, timezone
from typing import Dict, List

BASE_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_PATH, "data", "phalanx.db")
REPORTS_PATH = os.path.join(BASE_PATH, "reports")

def load_data() -> Dict:
    """Load all data from SQLite."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    
    c.execute("SELECT * FROM filings")
    filings = [dict(row) for row in c.fetchall()]
    
    c.execute("SELECT * FROM models")
    models = [dict(row) for row in c.fetchall()]
    
    c.execute("SELECT * FROM agents")
    agents = [dict(row) for row in c.fetchall()]
    
    c.execute("SELECT * FROM cycles ORDER BY cycle_id DESC LIMIT 1")
    last_cycle = c.fetchone()
    
    c.execute("SELECT severity, COUNT(*) as count FROM security_findings WHERE resolved = 0 GROUP BY severity")
    findings = {row[0]: row[1] for row in c.fetchall()}
    
    conn.close()
    
    return {
        "filings": filings,
        "models": models,
        "agents": agents,
        "last_cycle": dict(last_cycle) if last_cycle else {},
        "findings": findings,
        "timestamp": datetime.now(timezone.utc).isoformat()
    }

def generate_executive_report(data: Dict) -> str:
    """Generate executive summary markdown."""
    report = f"""# Phalanx Swarm v2.0-OMEGA — Executive Report

**Generated:** {data['timestamp']}
**Status:** FULLY AUTONOMOUS
**Agents:** 30/30 Active

---

## Financial Models

| Model | NPV ($B) | Status |
|-------|----------|--------|
"""
    for model in data['models']:
        npv = f"${model['npv_mean']:.2f}B" if model['npv_mean'] > 0 else f"DSCR {model['dscr_mean']:.2f}x"
        report += f"| {model['name']} | {npv} | {model['validation_status']} |\n"
    
    report += f"""
## Regulatory Filings

| Filing | Jurisdiction | Deadline | Days Left | Status | Risk |
|--------|-------------|----------|-----------|--------|------|
"""
    for filing in sorted(data['filings'], key=lambda x: x['days_remaining']):
        status_icon = "🔴" if filing['days_remaining'] < 0 else "🟡" if filing['days_remaining'] <= 7 else "🟢"
        report += f"| {filing['name']} | {filing['jurisdiction']} | {filing['deadline']} | {filing['days_remaining']} | {status_icon} {filing['status'].upper()} | {filing['risk_level'].upper()} |\n"
    
    report += f"""
## Security Posture

| Severity | Count |
|----------|-------|
"""
    for sev in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']:
        count = data['findings'].get(sev, 0)
        report += f"| {sev} | {count} |\n"
    
    total_findings = sum(data['findings'].values())
    report += f"\n**Total Open Findings:** {total_findings}\n"
    
    report += f"""
## System Health

- **Active Agents:** {len([a for a in data['agents'] if a['status'] == 'active'])}/30
- **Last Cycle:** {data['last_cycle'].get('cycle_id', 'N/A')}
- **Autonomous Status:** ONLINE
- **Next Cycle:** Every 5 minutes

---

*Report auto-generated by Phalanx Swarm v2.0-OMEGA*
"""
    
    return report

def generate_filing_report(data: Dict) -> str:
    """Generate detailed regulatory filing report."""
    report = f"""# Regulatory Filing Status Report

**Generated:** {data['timestamp']}

## Critical Path

"""
    
    critical = [f for f in data['filings'] if f['risk_level'] == 'critical']
    for filing in sorted(critical, key=lambda x: x['days_remaining']):
        pct = (filing['completed_items'] / filing['total_items']) * 100 if filing['total_items'] > 0 else 0
        report += f"""### {filing['id']}: {filing['name']}
- **Jurisdiction:** {filing['jurisdiction']}
- **Deadline:** {filing['deadline']} ({filing['days_remaining']} days)
- **Completion:** {pct:.0f}% ({filing['completed_items']}/{filing['total_items']})
- **Budget:** ${filing['budget_usd']:,}
- **HITL Required:** {'YES' if filing['hitl_required'] else 'NO'}
- **Status:** {filing['status'].upper()}

"""
    
    return report

def save_report(report: str, filename: str):
    """Save report to disk."""
    os.makedirs(REPORTS_PATH, exist_ok=True)
    path = os.path.join(REPORTS_PATH, filename)
    with open(path, 'w') as f:
        f.write(report)
    print(f"Report saved: {path}")
    return path

def main():
    print("Generating Phalanx Swarm reports...")
    
    data = load_data()
    
    exec_report = generate_executive_report(data)
    exec_path = save_report(exec_report, "executive_report.md")
    
    filing_report = generate_filing_report(data)
    filing_path = save_report(filing_report, "regulatory_report.md")
    
    # Save JSON for programmatic access
    json_path = os.path.join(REPORTS_PATH, "data_snapshot.json")
    with open(json_path, 'w') as f:
        json.dump(data, f, indent=2, default=str)
    
    print(f"\nReports generated:")
    print(f"  - {exec_path}")
    print(f"  - {filing_path}")
    print(f"  - {json_path}")
    
    return exec_path, filing_path

if __name__ == "__main__":
    main()
